# Generated by local compatibility updates.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("number", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=255)),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=255)),
                ("scale", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "company",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job", models.CharField(max_length=255)),
                ("post_type", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("job_place", models.CharField(max_length=255)),
                ("job_experience", models.CharField(max_length=255)),
                ("education", models.CharField(max_length=255)),
                ("min_wage", models.FloatField()),
                ("max_wage", models.FloatField()),
                ("job_duty", models.CharField(max_length=255)),
                ("job_benefits", models.CharField(max_length=255)),
                ("update_time", models.CharField(max_length=255)),
                (
                    "number",
                    models.ForeignKey(
                        db_column="number",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dataView.company",
                    ),
                ),
            ],
            options={
                "db_table": "job",
                "managed": True,
                "ordering": ["id"],
            },
        ),
    ]
